services:
  app:
    build: .
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_VERSION: ${APP_VERSION:-0.2.0}
    restart: unless-stopped
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
